[mypy]
files = src/
python_version = 3.11
platform = linux

strict = True
disallow_untyped_defs = true
warn_return_any = true
warn_unused_configs = true
disallow_any_explicit = false
disallow_any_generics = false
pretty = true

cache_dir = .mypy_cache/
show_error_codes = true

install_types = true
non_interactive = true

exclude = tests/
show_traceback = false
